# Generated by Django 5.1.2 on 2024-10-19 21:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('ano_modelo', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Etanol', 'Etanol'), ('Elétrico', 'Elétrico'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('quilometragem', models.PositiveIntegerField(default=0)),
                ('chassi', models.CharField(max_length=17, unique=True)),
                ('categoria', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Hatch', 'Hatch'), ('SUV', 'SUV'), ('Caminhão', 'Caminhão'), ('Moto', 'Moto')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Digite um CPF válido.')])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Digite um número de telefone válido.')])),
                ('data_contratacao', models.DateField()),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('concluida', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.veiculo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.vendedor')),
            ],
        ),
    ]
